apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-stateful
spec:
  serviceName: db-service
  updateStrategy:
    type: OnDelete
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db-container
          image: postgres:15
          ports:
            - containerPort: 5432
              name: "postgres"
          env:
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
          volumeMounts:
            - name: db-storage
              mountPath: "/var/lib/postgresql/data"
          resources:
            limits:
              memory: 512Mi
              cpu: "500m"
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-persisent-volume-claim
